"""Vera monorepo composition root."""

from .action_gate import (
    LifecycleBoundCoordinationBus,
    LifecycleEffectGateway,
    OutboundActionError,
    OutboundEffectResult,
)
from .coordination_command_journal import (
    CoordinationCommandBinding,
    CoordinationCommandJournal,
    CoordinationCommandJournalError,
    CoordinationCommandRecoveryAssessment,
    CoordinationCommandResult,
)
from .effect_recovery import (
    EffectRecoveryAuthorityError,
    EffectReconciliationProof,
    EffectReconciliationVerifier,
    HmacEffectReconciliationAuthority,
    LifecycleEffectRecovery,
    reconciliation_subject,
)
from .execution_adapters import (
    PCExecutionTransport,
    ProviderExecutionTransport,
)
from .lifecycle import (
    AcceptedLifecyclePermit,
    LifecycleActionDenied,
    LifecycleAssuranceError,
    LifecycleReconstruction,
    LifecycleReconstructionError,
    NativeLifecycleReceipt,
    NativeVeraLifecycle,
)
from .lifecycle_journal import (
    LifecycleEvent,
    LifecycleJournal,
    LifecycleJournalError,
)
from .outbound_audit import (
    OutboundAuditConsistency,
    OutboundAuditError,
    OutboundAuditEvent,
    OutboundExecutionAudit,
)
from .outbound_authority import (
    HmacPCJobAuthority,
    HmacProviderAuthority,
    OutboundAuthorityError,
    PCJobAuthorityProof,
    PCJobAuthorityVerifier,
    ProviderAuthorityEnvelope,
    ProviderAuthorityVerifier,
    pc_authority_subject,
    provider_authority_subject,
    validate_pc_authorization_binding,
)
from .outbound_trust import (
    AuthorityCurrentnessReceipt,
    AuthorityTrustState,
    OutboundTrustError,
    OutboundTrustRegistry,
)
from .pc_execution_binding import (
    PCExecutionBinding,
    PCExecutionBindingError,
    PCExecutionBindingStore,
    PCExecutionLease,
    PreparedPCDispatch,
)
from .qualified_pc import (
    PCExecutionRecoveryAssessment,
    PCJournalEventEvidence,
    QualifiedPCExecutionAdapter,
    QualifiedPCExecutionResult,
)
from .provider_execution_binding import (
    PreparedProviderDispatch,
    ProviderExecutionBinding,
    ProviderExecutionBindingError,
    ProviderExecutionBindingStore,
    ProviderExecutionRecoveryAssessment,
)
from .qualified_runtime import QualifiedVeraRuntime
from .reasoning_cascade import (
    CascadeEngine,
    CascadeOutcome,
    LayerResult,
    LayerSpec,
    ReasoningRequest,
)
from .registry import CAPABILITIES, LocalCapability, capability, validate_registry
from .task_execution import (
    CLOSEOUT_STATES,
    CLOSEOUT_SURFACES,
    TaskCloseout,
    TaskCloseoutAssessment,
    TaskCorrection,
    TaskEvent,
    TaskExecutionError,
    TaskExecutionLedger,
    TaskPacket,
    TaskState,
)
from .state import VeraStateDirectory, VeraStatePaths

__all__ = [
    "AcceptedLifecyclePermit",
    "AuthorityCurrentnessReceipt",
    "AuthorityTrustState",
    "OutboundTrustError",
    "OutboundTrustRegistry",
    "EffectRecoveryAuthorityError",
    "EffectReconciliationProof",
    "EffectReconciliationVerifier",
    "HmacEffectReconciliationAuthority",
    "LifecycleEffectRecovery",
    "reconciliation_subject",
    "CAPABILITIES",
    "CascadeEngine",
    "CascadeOutcome",
    "CoordinationCommandBinding",
    "CoordinationCommandJournal",
    "CoordinationCommandJournalError",
    "CoordinationCommandRecoveryAssessment",
    "CoordinationCommandResult",
    "LayerResult",
    "LayerSpec",
    "LifecycleActionDenied",
    "HmacPCJobAuthority",
    "HmacProviderAuthority",
    "OutboundAuthorityError",
    "PCJobAuthorityProof",
    "PCJobAuthorityVerifier",
    "ProviderAuthorityEnvelope",
    "ProviderAuthorityVerifier",
    "PCExecutionTransport",
    "ProviderExecutionTransport",
    "PCExecutionBinding",
    "PCExecutionBindingError",
    "PCExecutionBindingStore",
    "PCExecutionLease",
    "PCExecutionRecoveryAssessment",
    "PCJournalEventEvidence",
    "QualifiedPCExecutionAdapter",
    "QualifiedPCExecutionResult",
    "PreparedPCDispatch",
    "PreparedProviderDispatch",
    "ProviderExecutionBinding",
    "ProviderExecutionBindingError",
    "ProviderExecutionBindingStore",
    "ProviderExecutionRecoveryAssessment",
    "QualifiedVeraRuntime",
    "pc_authority_subject",
    "provider_authority_subject",
    "validate_pc_authorization_binding",
    "LifecycleAssuranceError",
    "LifecycleBoundCoordinationBus",
    "LifecycleEffectGateway",
    "LifecycleEvent",
    "LifecycleJournal",
    "LifecycleJournalError",
    "LifecycleReconstruction",
    "LifecycleReconstructionError",
    "LocalCapability",
    "NativeLifecycleReceipt",
    "OutboundAuditConsistency",
    "OutboundAuditError",
    "OutboundAuditEvent",
    "OutboundExecutionAudit",
    "OutboundActionError",
    "OutboundEffectResult",
    "NativeVeraLifecycle",
    "ReasoningRequest",
    "CLOSEOUT_STATES",
    "CLOSEOUT_SURFACES",
    "TaskCloseout",
    "TaskCloseoutAssessment",
    "TaskCorrection",
    "TaskEvent",
    "TaskExecutionError",
    "TaskExecutionLedger",
    "TaskPacket",
    "TaskState",
    "VeraStateDirectory",
    "VeraStatePaths",
    "capability",
    "validate_registry",
]
